services:
  postgres:
    image: postgres:18-alpine
    container_name: rms.postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_NAME} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask:
    container_name: rms.flask
    build: .
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://${DB_USER_NAME}:${DB_USER_PASSWORD}@postgres:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}

    volumes:
      - .:/app
      - /app/__pypackages__
    command: ["flask", "run", "--host=0.0.0.0"]

volumes:
  postgres_data: